package com.bccs.bsecure;

/**
 * Created by traci.kamp on 11/11/2014.
 * Created as a more efficient way of storing outgoing
 * messages in an app-created SQLite database since
 * the app cannot currently write to Android's default
 * outbox provider (default SMS app functionality not
 * implemented due to time constraints).
 */

public class myMessage {
    private int _id;
    private String _name;
    private String _number;
    private String _body;
    private boolean left;

    // Empty constructor
    public myMessage() {
    }

    // Specific constructor
    public myMessage(int ident, String cName, String cNum, String mBody) {
        this._id = ident;
        this._name = cName;
        this._number = cNum;
        this._body = mBody;
        this.left = true;
    }

    // Less-specific constructor
    public myMessage(String cName, String cNum, String mBody) {
        this._name = cName;
        this._number = cNum;
        this._body = mBody;
    }

    // Getter and setter methods, generated by Android Studio
    public int get_id() {
        return _id;
    }

    public void set_id(int id) {
        this._id = id;
    }

    public String get_name() {
        return _name;
    }

    public void set_name(String n) {
        this._name = n;
    }

    public String get_number() {
        return _number;
    }

    public void set_number(String num) {
        this._number = num;
    }

    public String getBody() {
        return _body;
    }

    public void setBody(String body) {
        this._body = body;
    }

    // General toString method. Prints contact name, number, and message body.
    public String toString() {
        return "Name: " + get_name() + " \nNumber: " + get_number() + " \nMessage: " + getBody();
    }

    public boolean getLeft() {
        return this.left;
    }

    public boolean isLeft() {
        return this.getLeft();
    }

    public void setLeft(boolean b) {
        this.left = b;
    }
}
